### ISSUE TITLE
Does the 1.9.4 version work on 1.10.2?

### ISSUE THREAD

**Issue by Claycorp** [elytra/LingeringLoot#2]
On CurseForge there is no 1.10.2 marked version, If the 1.9.4 version works can you please mark it as 1.10.2 capable? Thanks.

**Comment by alexbobp** [comment]
It does.  Good catch, I had forgotten to tag it.  It's updated.  Let me know if there are any issues.

**Comment by alexbobp** [comment]
(I assume you meant on curseforge.  reopen if you meant something else)
