### ISSUE TITLE
World Crash

### ISSUE THREAD

**Issue by Mattabase** [elytra/LingeringLoot#3]
The player was moving really quickly through a world and this crash happens whenever they open the world. 

https://goo.gl/AYRZcp

**Comment by alexbobp** [comment]
Was this on singleplayer?  (If so I have one suspicion...)

Would it be possible to share the modpack and the world so I can reproduce the issue?

**Comment by alexbobp** [comment]
Reopen this if you can provide information to reproduce

**Comment by Mattabase** [comment]
Oh sorry, I thought I responded to this issue. 

Yes it was singleplayer. 

I will see if I can reproduce this in a more consistent way and get back to you. The person who I am working on this for is the one who is crashing and it does not always happen. So I will look into it some more.

**Comment by alexbobp** [comment]
Sorry, I just noticed your reponse.  Another person has reported the same issue, so I am reopening this to link them.

**Comment by alexbobp** [comment]
Just a heads up, I linked a build on #4 that I am hoping remedies this issue.  If you can check it out, let me know if it resolves the issue.

**Comment by alexbobp** [comment]
According to PurpleHel (See #4) this is resolved in version 4.3 aka build 51/52.  Reopen if it doesn't resolve the issue for you
